apiVersion: v1
kind: Service
metadata:
  name: python-service-devops
  namespace: default
spec:
  ports:
  - nodePort: 32345
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: python_app
  sessionAffinity: None
  type: NodePort